# Generated by Django 5.1.3 on 2025-12-23 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_disabled_by_login_limit',
            field=models.BooleanField(default=False, verbose_name='Deshabilitado por Límite de Inicios'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_attempt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Intento de Inicio de Sesión'),
        ),
        migrations.AddField(
            model_name='user',
            name='login_count',
            field=models.IntegerField(default=0, verbose_name='Contador de Inicios de Sesión'),
        ),
        migrations.AddField(
            model_name='user',
            name='max_logins_allowed',
            field=models.IntegerField(default=2, verbose_name='Máximo de Inicios de Sesión Permitidos'),
        ),
        migrations.CreateModel(
            name='LoginReactivationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=10, verbose_name='Estado')),
                ('message', models.TextField(blank=True, verbose_name='Mensaje del Estudiante')),
                ('admin_response', models.TextField(blank=True, verbose_name='Respuesta del Administrador')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Procesamiento')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to=settings.AUTH_USER_MODEL, verbose_name='Procesado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactivation_requests', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Solicitud de Reactivación',
                'verbose_name_plural': 'Solicitudes de Reactivación',
                'ordering': ['-requested_at'],
            },
        ),
    ]
