# Generated by Django 5.2.8 on 2025-11-25 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Examen')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('subject', models.CharField(max_length=100, verbose_name='Materia')),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Puntuación Total')),
                ('passing_marks', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Puntuación Mínima')),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='Duración (minutos)')),
                ('exam_date', models.DateTimeField(verbose_name='Fecha del Examen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Exámenes',
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Puntuación Obtenida')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('graded', 'Calificado')], default='pending', max_length=20, verbose_name='Estado')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Calificación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.exam', verbose_name='Examen')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_results', to=settings.AUTH_USER_MODEL, verbose_name='Calificado por')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Resultado de Examen',
                'verbose_name_plural': 'Resultados de Exámenes',
                'ordering': ['-created_at'],
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
