# Generated by Django 5.2.8 on 2025-11-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_courseenrollment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tema', 'verbose_name_plural': 'Temas'},
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration_minutes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Duración (minutos)'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha del Tema'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exams/', verbose_name='Imagen del Tema'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='passing_marks',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Puntuación Mínima'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título del Tema'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='total_marks',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Puntuación Total'),
        ),
    ]
