# Generated by Django 5.2.8 on 2025-11-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_exam_options_alter_exam_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='exams/pdfs/', verbose_name='Archivo PDF'),
        ),
    ]
