# Generated by Django 5.1.3 on 2025-12-22 18:13

import django.core.validators
import exams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_exam_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp']), exams.models.validate_file_size], verbose_name='Imagen del Curso'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exams/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp']), exams.models.validate_file_size], verbose_name='Imagen del Tema'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='exams/pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf']), exams.models.validate_file_size], verbose_name='Archivo PDF'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp']), exams.models.validate_file_size], verbose_name='Imagen'),
        ),
    ]
